server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      # Account Service Route
      - id: account-service
        uri: lb://account-service
        predicates:
        - Path=/api/v1/accounts/**
      # Customer Service Route
      - id: customer-service
        uri: lb://customer-service
        predicates:
        - Path=/api/v1/customers/**
      # Notification Service Route
      - id: notification-service
        uri: lb://notification-service
        predicates:
        - Path=/api/v1/notifications/**
      # Statement Generation Service Route
      - id: statement-generation-service
        uri: lb://statement-generation-service
        predicates:
        - Path=/api/v1/statements/**
      # Transaction History Service Route
      - id: transaction-history-service
        uri: lb://transaction-history-service
        predicates:
        - Path=/api/v1/transactions/**
      # Discovery Server Route
      - id: discovery-service
        uri: http://localhost:8761
        predicates:
        - Path=/eureka/web
        filters:
        - SetPath=/
      # Discovery Service Static Resource Route
      - id: discovery-service-static
        uri: http://localhost:8761
        predicates:
        - Path=/eureka/**
