server:
  port: 8083

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/customer_db?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: examly
  jpa:
    hibernate:
      ddl-auto: update



