server:
  port: 8085

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: statement-generation-service
  datasource:
    url: jdbc:mysql://localhost:3306/statement_generation_db?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: examly
  jpa:
    hibernate:
      ddl-auto: update